### ISSUE TITLE
Authorization header in request problem on phone 

### ISSUE THREAD

**Issue by thuaung30** [thamardaw/HIDTCOPHospitalWeb#18]
**Issue** - When making request to api on localhost from react on mobile phone, 307 temporary redirect occurs. For example, a request to path "/api/patient" gets redirected to "/api/patient/" and as a result of redirection, the authorization header (Bearer token) got stripped and the authorized endpoints do not work anymore.

**Recommended Fix** - Add **trailing slash** to endpoints which require authorization. For example, fetching patient data url in PatientTable view should be changed from "/api/patient" to "/api/patient/".

@zay467 Please amend this fix and notify me when done.

**Comment by zay467** [comment]
@thuaung30 It is done. Pushed to dev branch.

**Comment by thuaung30** [comment]
@zay467 can you do it on a new branch? The dev branch is not up to date with the current staging and main thus when merged, there are gonna be huge merge conflicts, please checkout a new branch (add-trailing-slash or something) from current staging and add the trailing slash to the authorized routes. It is also a good practice to make use of short lived branches for these kind of fixes.

**Comment by zay467** [comment]
Pushed a new branch.... How do I delete the dev branch?

**Comment by thuaung30** [comment]
> Pushed a new branch.... How do I delete the dev branch?

git branch -d remote dev

**Comment by zay467** [comment]
pushed the new update. @thuaung30
